name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Install yalc
        run: yarn global add yalc

      - name: Publish local package
        run: yarn publish:local

      - name: Temporary uninstall renceng-native package
        run: yarn remove renceng-native --save
        working-directory: ./example

      - name: Add local package to ./example
        run: yarn add:local
        working-directory: ./example

      - name: Install on ./example
        run: yarn install
        working-directory: ./example

      - name: Test on ./example
        run: yarn test --passWithNoTests --ci --coverage --maxWorkers=2
        working-directory: ./example
